---
kind: pipeline
name: pr-testsonar

platform:
  os: linux
  arch: amd64

steps:
- name: build-maven
  image: maven
  commands:
  - mkdir -p build-artifacts
  - mvn clean install --gs settings.xml
  - cp target/common-services-skeleton-*.jar build-artifacts
  - ls build-artifacts

- name: sonar
  image: maven
  commands:
  - mvn sonar:sonar
  environment:
    MAVEN_OPTS: -Xmx512m
  depends_on:
  - build-maven

trigger:
  event:
  - push
  ref:
  - refs/heads/testsonar

---
kind: secret
name: maven_username

get:
  path: prod/maven
  name: username

---
kind: secret
name: maven_password

get:
  path: prod/maven
  name: password

---
kind: secret
name: sonar_token

get:
  path: prod/sonar
  name: token

---
kind: secret
name: sonar_github_token

get:
  path: prod/sonar
  name: github_token

---
kind: secret
name: nexus_username

get:
  path: push/nexus
  name: username

---
kind: secret
name: nexus_password

get:
  path: push/nexus
  name: password

...
